### ISSUE TITLE
FsUnit 2.3.2 tied to NUnit 3.5, so won't work with FsCheck.NUnit 2.7.0 which needs at least NUnit 3.6

### ISSUE THREAD

**Issue by marklam** [fsprojects/FsUnit#101]
### Description
The latest NuGet package for FsUnit (2.3.2) uses an out-of-date NUnit (3.5), so you can't use FsCheck.NUnit together with it, since it requires NUnit 3.6-or-greater.

**Comment by sergey-tihon** [comment]
could you please try and test latest alpha?
https://www.nuget.org/packages/FsUnit/2.4.0-alpha-1

**Comment by marklam** [comment]
It seems to require a pre-release of FSharp.Core (>= 4.0.1.7-alpha)

**Comment by sergey-tihon** [comment]
something wrong with it?
`FSharp.Core` is the only version of the package that contains '.net stardard' compatible version of `FSharp.Core` (together with the usual one)

**Comment by marklam** [comment]
I tried to install the FsUnit alpha with paket, but it didn't like the FSharp.Core alpha dependency because the other packages in the project had dependencies on "FSharp.Core ... (no prerelease)"

**Comment by sergey-tihon** [comment]
Please try latest [3.0.0-beta1](https://www.nuget.org/packages/FsUnit/3.0.0-beta1) it should works now

**Comment by marklam** [comment]
That works fine, thanks!
