### ISSUE TITLE
netstandard support for the other (xunit is a big one) FsUnit libraries

### ISSUE THREAD

**Issue by NinoFloris** [fsprojects/FsUnit#106]
It seems there is no FsUnit.Xunit netstandard support yet although the main package already got it in march. Would be nice to see this for the other packages as well

**Comment by sergey-tihon** [comment]
We did initial support in `3.0.0` and more accurate dependencies in `3.1.0-beta1`.
Please try the latest pre-release package and open another issue if you have any kind of issue with it.
