### ISSUE TITLE
Should have multiple target frameworks

### ISSUE THREAD

**Issue by baltie** [fsprojects/FsUnit#108]
If I create a new F# library project based on .NET Framework 4.7 and add the FsUnit 3.0.0 nuget package, I get a lot of additional nuget packages, supporting .net standard library 1.6.

My expectation would be that the FsUnit package targeted more than just .net standard 1.6, for instance .NET Framework 4.6 in addition. That way, I would only get FsUnit and not 40+ other packages as well.

**Comment by sergey-tihon** [comment]
Could you please try once again with [3.1.0-beta1](https://www.nuget.org/packages/FsUnit/3.1.0-beta1)?

**Comment by baltie** [comment]
Sorry, I never got around to test this. I've lately upgraded to FsUnit 3.1.0, and it works much better now, thank you. :)
