### ISSUE TITLE
You must add a reference to assembly 'nunit.framework'.

### ISSUE THREAD

**Issue by jchidley** [fsprojects/FsUnit#109]
### Description

I get this error:
The type referenced through 'NUnit.Framework.Constraints.Constraint' is defined in an assembly that is not referenced. You must add a reference to assembly 'nunit.framework'.

### Repro steps
Installed as per the instructions.

Visual Studio 2017
FsUnit 3.0.0
nunit 3.6.0 

```
    open NUnit.Framework
    open FsUnit
    1 |> should equal 1
```

this fails with the above error but

```
    Assert.AreEqual(1,1)
```

works fine.

**Comment by jchidley** [comment]
"Fixed" by downgrading to nunit 3.5.0

**Comment by sergey-tihon** [comment]
Could you please try once again with [3.1.0-beta1](https://www.nuget.org/packages/FsUnit/3.1.0-beta1)?

**Comment by sergey-tihon** [comment]
I believe this is also fixed already
