### ISSUE TITLE
contain on strings does not work as expected

### ISSUE THREAD

**Issue by dgfitch** [fsprojects/FsUnit#11]
I expected

    "This string is long" |> should contain "string"

to do something like a test framework's `Assert.Contains<string,string>`, and the error message I get was (at first) quite confusing:

    Test Name:	Test contain raw
    Test Outcome:	Failed
    Test Duration:	0:00:00.081

    Result Message:	
    Exception of type 'FsUnit.Xunit+MatchException' was thrown.
    Position: First difference is at position 0
    Expected: Contains string
    Actual:   was This string is long
    Result StackTrace:	
    at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher)
      at TestTestFramework.Test contain raw() in <snip>TestTestFramework.fs:line 13

**Comment by sergey-tihon** [comment]
`contain` operator designed for collections and does not work with strings.
Starting from [FsUnit.xUnit 1.4.0-beta2](https://www.nuget.org/packages/FsUnit.xUnit/1.4.0-beta2) we support new operator `haveSubstring` that works for your case
```fsharp
"This string is long" |> should haveSubstring "string"
```
See more samples [here](https://github.com/fsprojects/FsUnit/blob/master/tests/FsUnit.Xunit.Test/shouldHaveSubstringTests.fs)
