### ISSUE TITLE
The module/namespace 'NHamcrest' from compilation unit 'NHamcrest' did not contain the namespace, module or type 'CustomMatcher`1'

### ISSUE THREAD

**Issue by aggieben** [fsprojects/FsUnit#111]
### Description

I have created a new test (classlib) project using the dotnet sdk (2.0), and I'm using paket for package management.  I followed the xunit tutorial to get things wired up, and I am able to write a trivial xunit test to prove that the pieces work.  However, when I try to do that same with FsUnit.xUnit, the compiler fails thusly:

```
error FS0074: The type referenced through 'Xunit.Assert' is defined in an assembly that is not referenced. You must add a reference to assembly 'xunit'.
```

After configuring some binding redirects, the error becomes this:

```
FSC : error FS0193: The module/namespace 'NHamcrest' from compilation unit 'NHamcrest' did not contain the namespace, module or type 'CustomMatcher`1'
```

### Repro steps
1. Create project files as follows:

Contents of my `.fsproj`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net461</TargetFramework>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Test.fs" />
    <None Include="Script.fsx" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-xunit" version="2.3.0" />
  </ItemGroup>
  <Import Project="..\..\DotNetSdk.FscTooling.props" />
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

Contents of `DotNetSdk.FscTooling.props`:
```xml
<Project>
  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPLatform]::OSX)))' == 'true'">true</IsOSX>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPLatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'">
    <FscToolPath>/Library/Frameworks/Mono.framework/Versions/Current/Commands</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true'">
    <FscToolPath>/usr/bin</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
</Project>
```

Contents of `Test.fs`:
```F#
namespace Olo.Insights.Test
module Default =

    open Xunit
    open FsUnit.Xunit

    [<Fact>]
    let ``Simple test to prove fsunit`` () =
        true |> should be True
```

Contents of `packet.dependencies`:
```
source https://api.nuget.org/v3/index.json
generate_load_scripts: true

framework: net461
nuget FAKE
nuget FSharp.Core
nuget Rezoom.SQL.Provider.Postgres
nuget xunit ~> 2.3.0
nuget xunit.runner.visualstudio ~> 2.3.0
nuget dotnet-xunit ~> 2.3.0
nuget Microsoft.NET.Test.Sdk
nuget FsUnit.xUnit
```

Contents of `paket.references` in my test project:
```
FSharp.Core
xunit
FsUnit.xUnit
```

2. run `paket install`

3. run `dotnet build` or `msbuild`

### Expected behavior

Compile to succeed, 1 test to be discovered by the `dotnet xunit` runner.

### Actual behavior

Compiler error:
```
Test.fs(8,9): error FS0074: The type referenced through 'Xunit.Assert' is defined in an assembly that is not referenced. You must add a reference to  assembly 'xunit'.
```

4. After realizing that this was failing because of paket's dependency resolution algorithm, I specified `~> 3.0.0` in my `paket.dependencies` file.

5.  Now the original error is gone, and the correct versions are installed, but there seems to now be a conflict between the NHamcrest included in the FsUnit.xUnit nupkg and the NHamcrest my client fetched from nugget.

Example MSBuild output:
```
λ  msbuild
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/24/2017 06:20:25 PM.
Project "Test.fsproj" on node 1 (default targets).
_HandlePackageFileConflicts:
  Encountered conflict between 'Reference:C:\Users\ben\.nuget\packages\fsunit.xunit\3.0.0\lib\net45\NHamcrest.dll' and 'Reference:C:\Users\ben\.nuget\packages\nhamcrest\2.0.1\lib\net451\NHamcrest.dll'.  Choosing 'Reference:C
  :\Users\ben\.nuget\packages\nhamcrest\2.0.1\lib\net451\NHamcrest.dll' because AssemblyVersion '2.0.1.0' is greater than '1.2.1.0'.
  Encountered conflict between 'CopyLocal:C:\Users\ben\.nuget\packages\fsunit.xunit\3.0.0\lib\net45\NHamcrest.dll' and 'CopyLocal:C:\Users\ben\.nuget\packages\nhamcrest\2.0.1\lib\net451\NHamcrest.dll'.  Choosing 'CopyLocal:C
  :\Users\ben\.nuget\packages\nhamcrest\2.0.1\lib\net451\NHamcrest.dll' because AssemblyVersion '2.0.1.0' is greater than '1.2.1.0'.
```

Any ideas how to solve this?  I tried adding `copy_local` to my `paket.dependencies` file next to the reference to `FsUnit.xUnit`, but that didn't make a difference.

### Related information 

* Operating system: Windows 10
* Package Versions: FsUnit.xUnit 3.0.0, xunit* 2.3.0
* .NET Runtime, CoreCLR or Mono Version: .NET Framework 4.6.1, using dotnet sdk 2.0.2

**Comment by sergey-tihon** [comment]
Could you please try [3.1.0-beta1](https://www.nuget.org/packages/FsUnit.xUnit/3.1.0-beta1)?

**Comment by aggieben** [comment]
Yep, I gave that a try and it didn't seem to help.  I looked in my `projects.assets.json` which is created during the restore process, and I found this interesting:

```
{
  "version": 3,
  "targets": {
    ".NETFramework,Version=v4.6.1": {
      "FSharp.Core/4.2.3": {
        "type": "package",
        "compile": {
          "lib/net45/FSharp.Core.dll": {}
        },
        "runtime": {
          "lib/net45/FSharp.Core.dll": {}
        }
      },
      "FsUnit.xUnit/3.1.0-beta1": {
        "type": "package",
        "dependencies": {
          "NETStandard.Library": "1.6.0"
        },
        "compile": {
          "lib/net46/FsUnit.Xunit.dll": {}
        },
        "runtime": {
          "lib/net46/FsUnit.Xunit.dll": {}
        }
      },
```

This is just the first however many lines, but it shows the only dependency for `FsUnit.xUnit` being `NETStandard.Library` 1.6.0

**Comment by sergey-tihon** [comment]
Hmm... 🤔 no idea, NuGet UI show correct dependencies, so I expect that they should be installed ...

Maybe @enricosada could say what is wrong and what should be fixed?

<img width="404" alt="2017-10-27_1101" src="https://user-images.githubusercontent.com/1197905/32093801-5e58e8d8-bb06-11e7-84f3-ff42930ea1cc.png">

**Comment by alex-bogomaz** [comment]
FsUnit.Xunit 3.1.0-beta1 has following dependency section of NuSpec file:
```
<dependencies>
      <group>
        <dependency id="xunit" version="[2.3.0,2.4.0)" />
        <dependency id="NHamcrest" version="[2.0.1,2.1.0)" />
        <dependency id="FSharp.Core" version="[4.2.3,4.3.0)" />
      </group>
      <group targetFramework="netstandard1.6">
        <dependency id="NETStandard.Library" version="1.6.0" />
      </group>
</dependencies>
```
according to this SO answer https://stackoverflow.com/questions/34768539/nuget-doesnt-install-dependencies-when-targetframework-attribute-isnt-specif, 
since .NET Framework 4.6.1 (with .NET Core 2.0 SDK) implements "netstandard1.6" - 
the only dependendency for "FsUnit.Xunit 3.1.0-beta1" would be 
```
<dependency id="NETStandard.Library" version="1.6.0" />
```

**Comment by aggieben** [comment]
@alex-bogomaz why wouldn't xunit, NHamcrest (and even FSharp.Core) also be dependencies?

**Comment by alex-bogomaz** [comment]
My understanding is that "FsUnit.Xunit 3.1.0-beta1" package is not working for 
dotnet cli 2.0. This should be fixed. 
According to this
https://docs.microsoft.com/en-us/nuget/release-notes/NuGet-2.0:
```
There is no inheritance between groups. 
If a project's target framework matches the "targetFramework" attribute of a group, 
only the dependencies within that group will be installed.
```

In fact I was not able to compile simple XUnit test solution for net461 by simply referencing only
```<PackageReference Include="FsUnit.Xunit" Version="3.1.0-beta1" />```. 

but after referencing xunit, NHamcrest everything works (with some build warnings about assembly versions):
```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="FsUnit.Xunit" Version="3.1.0-beta1" />

    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="NHamcrest" Version="2.0.1" />

    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
```

**Comment by enricosada** [comment]
As a learned the bad way, the fallback references (the `All frameworks`) shown in nuget, should be avoided.
because if that exists, if target framework doesnt match EXACTLY (that mean version too), the fallback is going to be used, not the nearest one.

if your case, .net core 2.0 ask for `netstandard2.0`, but your nuspec doesnt have it, so fallback too `All frameowkrs` (the fallback group) and use .NET full assemblies.
Adding other pkg fix the situation because these pull in and override the packages.

So to fix:
- remove fallback group (the one without version)
- add a `net45` (or `net40`, etc) the minimal .NET version you support
- leave the `netstandard1.6` (will be used also for `netstandard2.0` because nearest)

**Comment by sergey-tihon** [comment]
this is crazy, thank you @enricosada  and @alex-bogomaz for an explanation.
I will push version with the fix soon

**Comment by sergey-tihon** [comment]
[FsUnit.xUnit 3.1.0-beta2](https://www.nuget.org/packages/FsUnit.xUnit/3.1.0-beta2) is released with per framework dependencies.

**Comment by aggieben** [comment]
@enricosada this is interesting, but I'm not sure I understand why the fallback group wouldn't have worked in my case, where I'm actually targeting `net461`.  Shouldn't the "All Frameworks" versions of these packages resolve for that target?

**Comment by sergey-tihon** [comment]
should not be an issue with v4 since it provide only `netstandard2.0` assemblies
