### ISSUE TITLE
support xunit 2.3.1

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/FsUnit#114]
If you create a new test project with Visual Studio 15.5.0 and add FsUnit.xunit, #110 is related.

![image](https://user-images.githubusercontent.com/80104/33676580-dab411de-da94-11e7-9fa9-5faee863bdf4.png)

**Comment by sergey-tihon** [comment]
could you please try the latest beta? https://www.nuget.org/packages/FsUnit.xUnit/3.1.0-beta2

**Comment by ctaggart** [comment]
Works great and the unit tests show up in Visual Studio now. I had to bump up the test project from `net45` to `net46` which is fine.
![image](https://user-images.githubusercontent.com/80104/33678470-8fc7e35c-da9a-11e7-9512-4a3716c3eb4e.png)

**Comment by ctaggart** [comment]
With company info pulled out, the fsproj was:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net46</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>../unity-packages/UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsUnit.xUnit" Version="3.1.0-beta2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.console" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>
</Project>
```
