### ISSUE TITLE
Update NuGet packages with new FSharp.Core version

### ISSUE THREAD

**Issue by irium** [fsprojects/FsUnit#116]
### Description

FsUnit and family requires FSharp.Core version < 4.3.0 while there is version 4.3.2 already published.

* Operating system
Windows 10 Pro
* Branch
FsUnit.xUnit @ 3.1.0-beta2
* .NET Core SDK 2.1.100-preview-007326

Visual Studio output:
```
Detected package version outside of dependency constraint: FsUnit.xUnit 3.1.0-beta2 requires FSharp.Core (>= 4.2.3 && < 4.3.0) but version FSharp.Core 4.3.2 was resolved.
```

**Comment by sergey-tihon** [comment]
I think this is also fixed in `3.1.0`. @irium Please reopen if I am wrong.
