### ISSUE TITLE
Support multi-target builds using Mono

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#118]
Tips here - https://github.com/dotnet/sdk/issues/335#issuecomment-368669050

**Comment by atlemann** [comment]
Hi! I'm working on this. Have never done a PR before, so I'm not sure how to proceed. I have forked the repo and created a branch which I have pushed to my fork. I made the build work using the proposed technique, but there is still stuff I want to fix. Should I open a [WIP] PR to here now?

**Comment by sergey-tihon** [comment]
Awesome! Yes, please open PR even with WIP version.
