### ISSUE TITLE
FsUnit.Expecto

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#120]
I think that would be nice to have an alternative assertion syntax for Expecto as well. A lot of people, including myself, like use the `FsUnit` DSL for assertions.

Awesome, @kleidemos did most of the work to make it happened. https://gist.github.com/kleidemos/35af85db392f21eaedc095b50c3c9449 The only missing piece is to decide how to merge it into `FsUnit`.

I see three option, ordered by my current preference.

### Option 1 (FsUnitTyped-like syntax, no NuGet package)

__Pros__:
- Type-safe assertions
- Backward compatibility with tests written using `FsUnitTyped` - http://fsprojects.github.io/FsUnit/FsUnitTyped.html#What-is-FsUnitTyped

__Cons__:
- Limited support for Expecto `Expect` module
- No `message` parameter in operator
- No NuGet package

### Option 2 (FsUnit-like syntax, release on NuGet)

__Pros__:
- Backward compatibility tests with  written using `FsUnit` - http://fsprojects.github.io/FsUnit/operators.html
- NuGet package 

__Cons__:
- Limited support for Expecto `Expect` module
- No `message` parameter in operator
- Not type-safe

### Option 3 (new syntax adapted for Expecto)

__Pros__:
- Better support of Expecto capabilities
- `message` parameter in operator
- NuGet package 

__Cons__:
- No compatibility with existing `FsUnit` implementations

What is the right way to go?

**Comment by jackfoxy** [comment]
Option 3. It has been a couple of years now since I have used FsUnit. I think Expecto would be best served by its own fluent composable assertion style.

**Comment by jackfoxy** [comment]
Maybe something like
(value1, value2) |> isEqual "error message"

**Comment by atlemann** [comment]
Doesn't Expecto already have something similar to `Option 1`,  which can be enabled by adding `open Expecto.Flip` in your test file. (https://github.com/haf/expecto/blob/master/Expecto/Flip.Expect.fs). I have never used the `FsUnitTyped syntax` before, only `FsUnit syntax`. To differentiate `FsUnit.Expecto` from `Expecto.Flip`, maybe Option 2 or 3 would be best?

**Comment by jackfoxy** [comment]
@atlemann  I didn't know about this. Thanks.

**Comment by jackfoxy** [comment]
I just started using Expecto.Flip today on the project I'm currently working on, and I like the syntax better. I think it would meet my composability needs (if I ever wanted/needed to compose Expecto results and property tests).

I'm not sure there is really a need for anything else.

**Comment by sergey-tihon** [comment]
Ok, I think that these are not enough reasons to compete with `Flip.Expect`
