### ISSUE TITLE
Make colors and indentation easier to distinguish information

### ISSUE THREAD

**Issue by WildYorkies** [fsprojects/FsUnit#122]
### Description

Users should be able to more easily see which tests failed and then see the related errors associated at a glance.

This is the red wall of text as it displays now:

![image](https://user-images.githubusercontent.com/1299322/42126514-ce011242-7c3e-11e8-8cda-5b5260cde89b.png)

### Possible Fixes

Only make the first `[xUnit.net 00:00:00.6835735]` lines **red**. And group the relevant details immediately underneath in **white** text.

This way, you're not repeating which test failed twice and the eye is immediately draw to which test failed and the user can easily ignore the details if they so wish.

```
Starting test execution, please wait...
[xUnit.net 00:00:00.6835735]     LeapTest.Year divisible by 4, not divisible by 100: leap year [FAIL]
  Error Message:
     FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
  Expected: Equals true
  Actual:   was False
  Stack Trace:
     at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher) in X:\FsUnit\src\FsUnit.Xunit\FsUnit.fs:line 19
[xUnit.net 00:00:00.6874387]     LeapTest.Year divisible by 400: leap year [FAIL]
  Error Message:
     FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
  Expected: Equals true
  Actual:   was False
  Stack Trace:
     at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher) in X:\FsUnit\src\FsUnit.Xunit\FsUnit.fs:line 19

Total tests: 4. Passed: 2. Failed: 2. Skipped: 0.
Test Run Failed.
```

**Comment by sergey-tihon** [comment]
Thank you for the issue @WildYorkies, but I do not think that it could be fixed in FsUnit.
I agree with you that color-coding is not perfect, but we don't control colors.

I have to close this issue =( I see that issues in xunit also was closed.
Would be better open the issue in VSTest repo.
