### ISSUE TITLE
Update to xUnit 2.4.0

### ISSUE THREAD

**Issue by ErikSchierboom** [fsprojects/FsUnit#123]
xUnit 2.4.0 was released recently. It would be nice if FsUnit would support this version.

**Comment by sergey-tihon** [comment]
@ErikSchierboom thanks for taking notice.

All (3) packages were releases with dependencies on latest unit testing frameworks

### 3.2.0 - Jul 30, 2018
* xunit (2.4)
* NUnit (3.10.1)
* MSTest.TestFramework (1.3.2)
* NETStandard.Library (2.0.3)

**Comment by ErikSchierboom** [comment]
Great, thanks!
