### ISSUE TITLE
docs link points to spam/malware website

### ISSUE THREAD

**Issue by samuela** [fsprojects/FsUnit#126]
### Description

On https://fsprojects.github.io/FsUnit/NUnit.html: "Thanks to Keith Nicholas and Julian from hubFS for [link]this example[/link]!" but it currently points to a sketchy website that's telling me to install Adobe Flash.

**Comment by sergey-tihon** [comment]
Thank you @sgoodgrove  for fixing this!

**Comment by sgoodgrove** [comment]
Thanks @sergey-tihon 
The t-shirt thing is the kick up the backside I needed to start contributing to the community. It’s low-hanging fruit initially, but I hope I can get better acquainted with some code bases and start making some more serious contributions.

P.S. thank you for all your hard work with F# Weekly!
