### ISSUE TITLE
Simple XUnit test fails only on Windows

### ISSUE THREAD

**Issue by pviotti** [fsprojects/FsUnit#138]
### Description

A simple test on Azure Pipelines fails only when using Windows (2016 or 2019).

### Repro steps

This is the very simple test: https://github.com/pviotti/sayit/blob/az-pipelines/SayIt.Tests/Tests.fs#L12-L18

[This](https://dev.azure.com/pviotti/gh-pipelines/_build/results?buildId=58&view=logs) is the build that is OK on Linux and Mac, but fails on Windows 2016.  
[Here](https://dev.azure.com/pviotti/gh-pipelines/_build/results?buildId=54&view=logs) the same build but with Windows 2019: 

This  is the failing exception:
```
  FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
Expected: Equals "sayit version 1.0.0.0
"
Actual:   was "sayit version 1.0.0.0
"
```

### Expected behavior

The test passes on every OS, since the code is exactly the same.

### Actual behavior

Only using a Windows agent the test doesn't pass.

### Known workarounds

N/A

### Related information 

* Operating system: Windows Server 2016 or 2019
* .NET Core 3.0

Packages versions:
- FsUnit.xUnit 3.5.0
- Microsoft.NET.Test.Sdk 16.3.0
- xunit 2.4.1
- xunit.runner.visualstudio 2.4.1
    <PackageReference Include="coverlet.collector" Version="1.1.0" />

**Comment by sergey-tihon** [comment]
I am not sure that it is somehow related to FsUnit at all.
Can you please try to play with your test, I guess it is platform specific issue (invisible character)
You probably should avoid `\n`  and use `TextWriter.CoreNewLine`, `Environment.NewLine` or [Trim()](https://docs.microsoft.com/en-us/dotnet/api/system.string.trim?view=netframework-4.8#System_String_Trim) both strings before comparison

**Comment by pviotti** [comment]
You're right, that was it, thanks!
