### ISSUE TITLE
`should equal` fails when `Assert.Equal` doesn't

### ISSUE THREAD

**Issue by ittennull** [fsprojects/FsUnit#146]
### Description

`should equal` fails when `Assert.Equal` doesn't

### Repro steps

```f#
module SomethingIsWrong

open System.Threading.Tasks
open FSharp.Control.Tasks.V2.ContextInsensitive
open FsUnit.Xunit
open FsUnit.CustomMatchers
open Xunit

[<Fact>]
let test () = task{
    let! result = task{
        match! Task.FromResult(Error "error") with
        | Error error -> return Error error 
        | Ok _ -> return Ok()
    }
    
    // works 
    result = Error "error" |> should equal true
    
    // works
    Assert.Equal(result, Error "error")
    
    // fails
    result |> should equal (Error "error")
}
```

### Expected behavior

The test passes

### Actual behavior

`should equal` fails with "FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
Expected: Equals Error "error"
Actual:   was Microsoft.FSharp.Core.FSharpResult`2[Microsoft.FSharp.Core.Unit,System.String]"

### Related information 

* Linux 5.4.2-1-MANJARO
* dotnet sdk 3.1.100
* FsUnit.xUnit 3.8.0

**Comment by CaptnCodr** [comment]
I figured it out and have a solution for you. 

In your last assertion you may have to add the explicit type to your `Error`, e.g.:
`result |> should equal (Result<unit, string>.Error "error")`

I'm very surprised that the compiler can't infer the type for this assertion.

**Comment by abelbraaksma** [comment]
Maybe it's a type inference bug in F#? Is there a simpler test that doesn't involve task that exhibits the same behavior?

**Comment by CaptnCodr** [comment]
I tested it with a simpler example which results in a same way:
```
match Error "error" with
        | Error error -> Error error 
        | Ok _ -> Ok ()

result |> should equal (Error "error")
```

The `match` expression is the neck braker here. 

I think the `Assert.Equal(result, Result.Error "error")` has an internal `bind` to infer the correct type.

**Comment by CaptnCodr** [comment]
@sergey-tihon What do you think?
I would suggest to close this issue, because everything looks fine here.

**Comment by CaptnCodr** [comment]
@ittennull Did it help? 
You could close this issue when there aren't any questions to this topic.

So long!
