### ISSUE TITLE
Parameterized tests with TestCaseSource attribute not working

### ISSUE THREAD

**Issue by svdHero** [fsprojects/FsUnit#149]
### Description

I want to run parameterized test using the NUnit attribute `TestCaseSource`. Please tell me how to do that and add code examples for paremterized tests to the documentation on https://fsprojects.github.io/FsUnit/NUnit.html.

### Repro steps

Run the code snippet
```fsharp
namespace FooSpace

module FooTests =
    
    open NUnit.Framework
    open FsUnit

    let mySrc1 = [|
            (17, "One", 1.5);
            (42, "Two", 2.3);
        |]

    let mySrc2 = [|
            [| (17, "One", 1.5) |];
            [| (42, "Two", 2.3) |];
        |]

    let mySrc3 = seq {
            yield (17, "One", 1.5)
            yield (42, "Two", 2.3)
        }

    [<Test>]
    [<TestCaseSource("mySrc1")>]
    let testFoo (testData: int * string * float) =
        let foo, bar, umu = testData
        1 |> should equal 1
```
Note that I tried different flavours of test case sources above, based on (rather old) search results from the web like, e.g.

* https://stackoverflow.com/a/35733745/3760986
* http://hombredequeso.id.au/2014/06/20/fsunit-data-driven-tests.html
* https://winterlimelight.com/2016/12/20/fsunit/
* http://andy-p.github.io/FsTestCaseSource.html

### Expected behavior

A `dotnet test` discovers two test cases, both are run and succeed.

### Actual behavior

Two test cases are discovered and run, but both fail with the error message
```
Not enough arguments provided, provide at least 3 arguments.
  Exception doesn't have a stacktrace
```
no matter if one uses `mySrc1`, `mySrc2` or `mySrc3`.

### Known workarounds

None.

### Related information 

* Windows 8.1
* FsUnit Release 3.8.0
* .NET Core 3.1

**Comment by CaptnCodr** [comment]
Hey @svdHero,
the testing framework needs a test class -> [setup, examples](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-nunit).

When you follow these instructions (provided above) then you have a test class with members in it.

I've also wrote down the appropriate code for you:
```
namespace FooSpace

open NUnit.Framework
open FsUnit

[<TestFixture>]
type FooTests () = 

    static member mySrc1 () = [|
            (17, "One", 1.5)
            (42, "Two", 2.3)
        |]

    static member mySrc2 = [|
            [| (17, "One", 1.5) |]
            [| (42, "Two", 2.3) |]
        |]

    static member mySrc3 = seq {
            (17, "One", 1.5)
            (42, "Two", 2.3)
        }

    [<Test>]
    [<TestCaseSource("mySrc1")>]
    member this.testFoo (testData: int * string * float) =
        let foo, bar, umu = testData
        1 |> should equal 1
```

Everything looks and works fine.

**Comment by svdHero** [comment]
@CaptnCodr I am confused now. According to example 1 of the [FSUnit documentation](https://fsprojects.github.io/FsUnit/NUnit.html) a `TestFixture` is not necessary.

Also, I have hundreds of other FsUnit tests without any `TestFixture` that run just fine. The problem only exists with parameterized tests that use a `TestCaseSource`.

**Comment by CaptnCodr** [comment]
`[<TestFixture>]` is in this case optional and `[<Test>]` is optional when you have `[<TestCase>]` or `[<TestCaseSource()>]`.

Try it out.

**Comment by svdHero** [comment]
I've just found that, too, in, [the official NUnit documentation](https://github.com/nunit/docs/wiki/TestFixture-Attribute). However, there it clearly says:

> Beginning with NUnit 2.5, the TestFixture attribute is optional for non-parameterized, non-generic fixtures. **So long as the class contains at least one method marked with the Test, TestCase or TestCaseSource attribute, it will be treated as a test fixture**.

For me that means:

1. My Test Class itself is not parameterized, i.e., it has no explicit constructor.
2. My Test Class contains a method marked with the `TestCaseSource` attribute.

Hence, according to the documentation above, it should be treated as a test fixture without any problem. So what's wrong with my code?

**Comment by svdHero** [comment]
Or in other words: the only difference between my code and your code, @CaptnCodr , is the `TestFixture` attribute, right? So if this attribute is optional anyway, why does your code run, but mine does not?

**Comment by svdHero** [comment]
Ah, sorry. My fault. I only now saw the `member` keyword. I got it. The class is necessary. Let me try...

**Comment by svdHero** [comment]
Ok, that works.
Funnily enough, I also found a different solution on F# Slack for my original code without the need of a test fixture class:

```fsharp
namespace FooSpace

module FooTests =
    
    open NUnit.Framework
    open FsUnit

    let mySrc : obj[][] = [|
            [| 17; "One"; 1.5 |]
            [| 42; "Two"; 2.3 |]
        |]

    [<Test>]
    [<TestCaseSource("mySrc")>]
    let testFoo (testData: int * string * float) =
        let foo, bar, umu = testData
        1 |> should equal 1
```
Apparently, the boxing of the array via type hint `obj[][]` makes the error message go away. @CaptnCodr do you have any idea why this works without a test class / test fixture?

**Comment by CaptnCodr** [comment]
@svdHero I don't really know. 
I'm surprised that the implicit conversion from array to tuple works.

**Comment by svdHero** [comment]
Okay. Well. Thanks for your help anyway. I'm closing this issue.
