### ISSUE TITLE
"should haveCount" does not work on an IEnumerable because it has a function Count and not a property Count

### ISSUE THREAD

**Issue by remkoboschker** [fsprojects/FsUnit#15]
Are there any reasons not to add an overload that calls the function?

**Comment by sergey-tihon** [comment]
`FsUnit` implementation of `haveCount` sit on top of `NUnit` `Has.Count` constraint.
`NUnit` authors are not going to support `.Count()` scenario ( [read more here](https://github.com/nunit/nunit/issues/158) )

I believe that we should not override `NUnit` behavior in `FsUnit`.
