### ISSUE TITLE
Equality check fails for Dictionaries inside records

### ISSUE THREAD

**Issue by svdHero** [fsprojects/FsUnit#152]
### Description
When a Dictionary is a named value inside a record, then FsUnit / FsUnitTyped produces an error when calling `should equal` and `shouldEqual`, respectively, although, according to the test output, the compared values are equal, e.g.:
```
 Expected: <{ Dict = seq [[Hello, 7]; [World, 8]] }>
 But was:  <{ Dict = seq [[Hello, 7]; [World, 8]] }>
```

### Repro steps

Execute this in a test runner:
```fsharp
namespace UnitTests

module MyWrappedDictTests =
    
    open NUnit.Framework
    open FsUnit
    open FsUnitTyped

    type MyDict = System.Collections.Generic.IDictionary<string,int>

    type MyWrappedDict = {
        Dict : MyDict
        }

    let dictOne : MyDict = [("Hello", 7); ("World", 8)] |> dict

    let dictTwo : MyDict = [("Hello", 7); ("World", 8)] |> dict

    let wrappedDictOne : MyWrappedDict = {
        Dict = dictOne
        }

    let wrappedDictTwo : MyWrappedDict = {
        Dict = dictTwo
        }

    [<Test>]
    let dictionaryEquality_WithFsUnit () =
        dictOne |> should equal dictTwo

    [<Test>]
    let dictionaryEquality_WithFsUnitTyped () =
        dictOne |> shouldEqual dictTwo

    [<Test>]
    let wrappedDictionaryEquality_WithFsUnit () =
        wrappedDictOne |> should equal wrappedDictTwo

    [<Test>]
    let wrappedDictionaryEquality_WithFsUnitTyped () =
        wrappedDictOne |> shouldEqual wrappedDictTwo

```
### Expected behavior

All four tests succeed.

### Actual behavior

The last two tests with the wrapped Dictionaries fail.

### Known workarounds

None.

### Related information 

* Windows 8.1
* FsUnit 3.8.0 from NuGet
* .NET Core 3.1

**Comment by CaptnCodr** [comment]
Short:
`wrappedDictOne` and `wrappedDictTwo` have different hash codes and there is no structural equatable available.

PR #147 could solve this issue.

Workaround:
You can use `equivalent` in FsUnit and access dictionaries via these options:
1. `wrappedDictOne.Dict |> should equivalent wrappedDictTwo.Dict`
2. `wrappedDictOne.Dict |> should equal wrappedDictTwo.Dict`
3. `wrappedDictOne.Dict |> shouldEqual wrappedDictTwo.Dict`

`equivalent` was implemented for `IEnumerable`s but here work are all three options.

**Comment by sergey-tihon** [comment]
Agree, we not going to implement / support structural equality for types that does not implement it themself.
In v4 we added support for `IStructuralComparable` & `IStructuralEquatable `
https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.NUnit/Equality.fs#L22-L25
