### ISSUE TITLE
How to execute async tests?

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FsUnit#153]
Is there an adapter that allows executing tests of `async` workflows?

**Comment by sergey-tihon** [comment]
What framework do you use?
FsUnit is an assertion library. Execution of test is the responsibility of test framework

**Comment by xperiandri** [comment]
NUnit
But there is no sample neither for MsTest, not xUnit. The only way is to do `|> Async.StartImmediateAsTask :> Task`

**Comment by xperiandri** [comment]
As **FsUnit** provides F# abstraction on top of frameworks it is **FsUnit** responsibility to do adaptation

**Comment by sergey-tihon** [comment]
You solution is fine, here you also can find good recommendations
https://stackoverflow.com/questions/46227709/how-do-i-write-an-async-unit-test-method-in-f

my personal choice will be to use `task{}` and do not convert each async to task in tests
