### ISSUE TITLE
Add "isUnionCase" function

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FsUnit#16]
Based on [this SO question](http://stackoverflow.com/questions/19001567/how-to-check-the-case-of-a-discriminated-union-with-fsunit), I think that adding function `isUnionCase` would be pretty useful for testing.

(Or similar functionality exposed in some nicer FsUnit-friendly way, like `should (beCase <@ Foo @>)`)

**Comment by sergey-tihon** [comment]
Implemented by #134
