### ISSUE TITLE
FSharpCustomMessageFormatter

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#166]
Just found in docs http://fsprojects.github.io/FsUnit/NUnit.html
<img width="847" alt="image" src="https://user-images.githubusercontent.com/1197905/87973332-04756700-cad1-11ea-9884-2e96b0627ec3.png">

@CaptnCodr I remember that you fixed similar issues here https://github.com/fsprojects/FsUnit/pull/155
May I ask you to take look if it still works / needed?

**Comment by CaptnCodr** [comment]
Yes, I take a look.

**Comment by CaptnCodr** [comment]
@sergey-tihon It still works and is needed. Especially the `Result`-Type.
In this repro I recognized that `FsUnitTyped.shouldEqual` and `FsUnitTyped.shouldNotEqual` prints the error message twice.
First from `FsUnitTyped` and second from the Nunit framework:

![image](https://user-images.githubusercontent.com/4574031/87976875-1acdf380-cace-11ea-9c47-43597140ffd3.png)

We should fix this. This is from here: https://github.com/fsprojects/FsUnit/pull/147/commits/bf38605414faaf8fc87a1ebbef1876d5b6190e65#diff-fc2f5b7136e6efc18391b4ff8daa5d05R11

**Comment by CaptnCodr** [comment]
This fix can be achieved through removing the `sprintf "Expected: %A\nActual: %A" expected actual`, but then we have no pretty print anymore.
