### ISSUE TITLE
shouldFail with "unexpected result" instead of ignore

### ISSUE THREAD

**Issue by jilleJr** [fsprojects/FsUnit#174]
### Description

Using `shouldFail` is a little bit tedious when it comes to having to use `ignore`.

In my opinion, would be nice if `shouldFail` could take a function that had a return value (i.e. `unit -> 'a`) and then use that return value in the error message if the test would fail.

### Repro steps

1. Create MyTests.fs

2. Insert code:

   ```fs
   module MyTests

   open System
   open NUnit.Framework
   open FsUnitTyped

   [<TestCase("foo")>]
   [<TestCase("42")>] // valid int, shouldFail will trigger
   let ``Throws on invalid int`` input =
       // want to do:
       // let operation () = Convert.ToInt32 input
       let operation () = Convert.ToInt32 input |> ignore
       shouldFail operation

   [<Test>]
   let ``Parses int`` () =
       Convert.ToInt32 "123" |> shouldEqual 123
   ```

3. Run tests

### Expected behavior

Error from first test should show:

```
 Throws on invalid int("42")
   Source: UtilityTests_Math.fs line 13
   Duration: 53 ms

  Message: 
    System.Exception : Operation did not fail.
    Unexpected result: 42
  Stack Trace: 
    TopLevelOperators.shouldFail[exn](FSharpFunc`2 f)
    UtilityTests_Math.Throws on invalid int(String input) line 13
```

### Actual behavior

Error thrown:

```
 Throws on invalid int("42")
   Source: UtilityTests_Math.fs line 13
   Duration: 53 ms

  Message: 
    System.Exception : Operation did not fail.
  Stack Trace: 
    TopLevelOperators.shouldFail[exn](FSharpFunc`2 f)
    UtilityTests_Math.Throws on invalid int(String input) line 13
```

### Related information 

* Operating system: Windows
* FsUnitTyped: 2.3.2
* .NET Runtime, CoreCLR or Mono Version: .NET 4.5.1

**Comment by CaptnCodr** [comment]
Hi, 
do I understand right that you want to have an information what exactly goes wrong in `shouldFail` like `Unexpected result: 42`?
![image](https://user-images.githubusercontent.com/4574031/97846040-b6861700-1ced-11eb-94ce-8f92be0e0c98.png)
That means, that the value of `But was: null` would be `But was: 42`?

**Comment by jilleJr** [comment]
@CaptnCodr Yea that would be swell! Maybe pronounce that one is a value and one is an exception a little more.

(Just brainstorming) what about:

1. Expected: instance of `<System.Exception>`  
   But returned: 42

2. Expected exception: instance of `<System.Exception>`  
   But returned: 42

3. Expected: exception of `<System.Exception>`  
   But returned: 42

And then have on wrong exception type it shows:

- Expected: exception of `<System.ArgumentNullException>`  
  But threw: exception of `<System.Exception>`

Just in an effort to make the distinction between unexpected results and wrong exceptions unambiguous in the error messages.

**Comment by CaptnCodr** [comment]
Short: This behaviour is not idiomatic to FsUnit.

Long: This messages you see are the result of the checks in Nunit (in this case). 
This operator `shouldFail` works with `Assert.Throws` and ignores the returning/deviating exception, it only checks the type of the actual code and creates a delegate for your function to run it. In addition `Assert.Throws` takes a [TestDelegate](https://docs.nunit.org/articles/nunit/writing-tests/assertions/classic-assertions/Assert.Throws.html) which takes unit->unit.

You may have to rethink your testing code to fit into it or you build your own helper functions that fits into your code.
Another way: You build it with NUnit functions (`Assert.Throws`, `Assert.Equal`, `Assert.That`). 😉 

Questions? -> Ask. 🙂

**Comment by jilleJr** [comment]
Hmm ok yea. I mean it would be possible to reinvent the wheel a little and abuse the `Assert.Fail()` with a custom check and custom error message. But maybe that's too non-idiomatic to FsUnit as you say.

The whole point was just to get better error messages (and less `|> ignore`), and not necessarily that users should rely on this new behaviour.

It's OK for me to close this issue.

**Comment by CaptnCodr** [comment]
Perhaps, I will look into this at another point. It have to fit in all structures and it's a clump of work to do so.

If you have a proposal of an implementation don't hesitate to open a PR.

**Comment by CaptnCodr** [comment]
@jilleJr You can close this issue. There is no plan to do it. 
Actually, there is no great need to use it. There are more ways to test code using other operators.

**Comment by jilleJr** [comment]
Oki ^^
