### ISSUE TITLE
Extend maintainers team

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#175]
@CaptnCodr you recently did a great job fixing issues in this repo.
Would you like to become a maintainer of FsUnit, receive full access to the repo, nuget packages and help keep this project being actual?

**Comment by CaptnCodr** [comment]
I'm happy that you ask. Yes, I want to become a maintainer of FsUnit.

**Comment by sergey-tihon** [comment]
@CaptnCodr give me please you NuGet account name

**Comment by CaptnCodr** [comment]
Nuget is same as GitHub username.

**Comment by CaptnCodr** [comment]
Thank you very much @sergey-tihon. 😊🥳

**Comment by sergey-tihon** [comment]
Thank you @CaptnCodr for your contributions!
