### ISSUE TITLE
System.NullReferenceException generated if bindings are outside of [<Fact>] attributed let binding

### ISSUE THREAD

**Issue by bmitc** [fsprojects/FsUnit#179]
### Description

I am having some issues in which a `System.NullReferenceException` is generated if I pull some bindings outside of a test's let binding with the `[<Fact>]` attribute. The use case is that if multiple tests use the same values, it would be nice to simply define them once outside of the tests rather than have to copy them into each test. This seems to work for some situations but not all. The behavior is inconsistent, and I'm not sure what triggers the exception.

What's weird is that I've done this in some cases where it worked as expected, but in this and other cases, it generates this exception.

### Repro steps

1. Open up the attached solution.

2. Navigate to `world.fs` in the `XUnitTests` project.

3. Note the code:
    ```
    // Parameters used across many tests
    let light = {Position = point(-10.0, 10.0, -10.0); Intensity = color(1.0, 1.0, 1.0)}
    let m = {material() with Color = color(0.8, 1.0, 0.6); Diffuse = 0.7; Specular = 0.2}
    let t = Scaling(0.5, 0.5, 0.5)
    let s1 = {sphere with Material = Some m}
    let s2 = {sphere with Transform = Some t}
    let w = {Objects = [s1; s2]; LightSource = light}

    [<Fact>]
    let ``The default world`` () =
        // If the parameters are copied here, there is no exception
        (w.LightSource, List.contains s1 w.Objects, List.contains s2 w.Objects) |> should equal (light, true, true)

    [<Fact>]
    let ``Intersect a world with a ray`` () =
        // If the parameters are copied here, there is no exception
        let r = ray (point(0.0, 0.0, -5.0)) (vector(0.0, 0.0, 1.0))
        let xs = intersectWorld w r
        xs |> List.map (fun x -> x.Time) |> should equal [4.0; 4.5; 5.5; 6.0]
    ```

4. Run the tests. Note that these two tests generate the error `System.NullReferenceException : Object reference not set to an instance of an object.`

5. Cut the bindings from `light` to `w` into both tests in the commented spot.

6. Re-run the tests and note that no exception is generated.

### Expected behavior

I would expect these bindings to work as they normally do in F# and that no exception is generated. I.e., both scenarios should execute in the same way.

### Actual behavior

An exception is generated: `System.NullReferenceException : Object reference not set to an instance of an object.`

### Known workarounds

Duplicate the bindings for every test that needs them.

### Related information 

* Windows 10 (version 2004, build 19041.630)
* .NET Core 3.1
    Also,
    ```
    <PackageReference Include="FsUnit.xUnit" Version="4.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
    ```

[RayTracerChallenge.zip](https://github.com/fsprojects/FsUnit/files/5585999/RayTracerChallenge.zip)

**Comment by CaptnCodr** [comment]
Hey @bmitc, I looked at your code and you may have to put your test code into a class because the compiler put `let` bindings out of the scope. This is a general problem from the compiler.

The best fix looks like this:
```
type WorldTests () =

    // Parameters used across many tests
    let light = {Position = point(-10.0, 10.0, -10.0); Intensity = color(1.0, 1.0, 1.0)}
    let m = {material() with Color = color(0.8, 1.0, 0.6); Diffuse = 0.7; Specular = 0.2}
    let t = Scaling(0.5, 0.5, 0.5)
    let s1 = {sphere with Material = Some m}
    let s2 = {sphere with Transform = Some t}
    let w = {Objects = [s1; s2]; LightSource = light}

    [<Fact>]
    member _.``The default world`` () =
        // If the parameters are copied here, there is no exception
        (w.LightSource, List.contains s1 w.Objects, List.contains s2 w.Objects) |> should equal (light, true, true)

    [<Fact>]
    member _.``Intersect a world with a ray`` () =
        // If the parameters are copied here, there is no exception
        let r = ray (point(0.0, 0.0, -5.0)) (vector(0.0, 0.0, 1.0))
        let xs = intersectWorld w r
        xs |> List.map (fun x -> x.Time) |> should equal [4.0; 4.5; 5.5; 6.0]
```

This is not a problem from FsUnit or the test framework. In nunit you will get the same issues.

**Comment by bmitc** [comment]
Thanks for taking a look! My issue was part is there something wrong or am I doing something wrong, so this helps.

Although, I think I am still a little confused. For example, in the `LightAndShading.fs` test file, I have `let` bindings not in a class like this,
```
// The next level up is a module, not a class.

let m = material()
let position = point(0.0, 0.0, 0.0)

[<Fact>]
let ``Lighting with the eye between the light and the surface`` () =
    let eyev = vector(0.0, 0.0, -1.0)
    let normalv = vector(0.0, 0.0, -1.0)
    let light = {Position = point(0.0, 0.0, -10.0); Intensity = color(1.0, 1.0, 1.0)}
    lighting m light position eyev normalv |> should equal (color(1.9, 1.9, 1.9))
```
and those work fine. And in [this example](http://fsprojects.github.io/FsUnit/xUnit.html#BowlingGame) on the FsUnit website, there are also some bindings outside of the `[<Fact>]` tests. So I think it's unclear why this works sometimes and doesn't work other times.

Any thoughts?

**Comment by CaptnCodr** [comment]
Yes, I think that's a difference between a class and a record.

Here you have a instance of a class:
> `let position = point(0.0, 0.0, 0.0)`

and here a record instantiation:
> `let w = {Objects = [s1; s2]; LightSource = light}`

Their behaviour may be different.

**Comment by bmitc** [comment]
In that code, `material` and `point` are both functions that return records, which is why they are lower case. They're simply like that to provide easier record creators and to match the book I'm going through. In the ones that cause errors, `light` through `w`, those are all records as well. None of these records have F# class types in their underlying data.

**Comment by CaptnCodr** [comment]
Yes, I see. 

Perhaps, the encapsulation is responsible for holding your data.
E.g.: make everything a function you'll don't lose your data while running tests. 
Disadvantage: you have many parantheses in your code.

**Comment by CaptnCodr** [comment]
@bmitc Everything clear? Can this be closed?

**Comment by bmitc** [comment]
Apologies, I didn't see your last message.

I think it's clear what to do to fix it. For data that is re-used across multiple tests, it seems the options are:

1. enclose tests and pieces to be reused across them inside a class,
2. put reusable bindings behind function calls,
3. repeat data for each test.

It isn't necessarily clear as to why, since that requires knowledge of the xUnit framework and how the tests are built. I do think an appropriate action item out of this would be to update the documentation since this does not follow as expected from normal F# development.

I'd be happy to help out there. I happened to notice that the samples link is broken [here](https://fsprojects.github.io/FsUnit/#Contributing). There should be a section or sample somewhere that explains this limitation and how to handle it.

**Comment by CaptnCodr** [comment]
>It isn't necessarily clear as to why, since that requires knowledge of the xUnit framework and how the tests are built. I do think an appropriate action item out of this would be to update the documentation since this does not follow as expected from normal F# development.

Yes, you maybe should know which framework you use in your project and why. In fact that the xUnit framework is written in C#, perhaps it has same behaviours like architectures that are written in C#. 
That includes that you encapsulate your bindings in a class which are in samples here: http://fsprojects.github.io/FsUnit/xUnit.html#LightBulb
Yes, there is no notice that are used with types (class types).

>I'd be happy to help out there. I happened to notice that the samples link is broken here. There should be a section or sample somewhere that explains this limitation and how to handle it.

Thanks for pointing out. The samples are catogorized in their test frameworks in topic `GETTING STARTED`. 

P.S.: http://fsprojects.github.io/FsUnit/ is the recommended github page not https://fsprojects.github.io/FsUnit/
