### ISSUE TITLE
FsUnit does not work with Result

### ISSUE THREAD

**Issue by purkhusid** [fsprojects/FsUnit#189]
### Description

FsUnit does not work with Result type

### Repro steps

Please provide the steps required to reproduce the problem

```
type DomainError =
| ThisIsAnError of string

let doStuff a = if a = 0 then Error(DomainError.ThisIsAnError("yo")) else Ok("yeehaw")

[<Fact>]
let ``Testing stuff`` () =
    // Arrange
    let expectedError =
        Error(DomainError.ThisIsAnError("yeehaw"))

    // Act
    let result =
        doStuff 1337

    // Assert
    result |> should equal expectedError
```

### Expected behavior

The test should pass

### Actual behavior

Fails with

```
Expected: Equals Error (Unauthorized "yeehaw")
      Actual:   Error (Unauthorized "yeehaw")
```

### Related information 

Using FsUnit.Xunit 4.0.4

**Comment by CaptnCodr** [comment]
Hello @purkhusid, 
when I run your code then I get this message:
```fsharp
FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
Expected: Equals Error (ThisIsAnError "yeehaw")
Actual:   Ok "yeehaw"
```
The expected `Error` doesn't match with the actual `Ok`.
I played with your example and I think you have to specify the type like that (which works):
```fsharp
[<Fact>]
let ``Testing stuff`` () =
    // Arrange
    let expectedError : Result<string, DomainError> =
        Error(DomainError.ThisIsAnError("yo"))

    // Act
    let result : Result<string, DomainError> =
        doStuff 0

    // Assert
    result |> should equal expectedError
```
In your example the compiler doesn't "know" your type in expectedError (`Result<'a, DomainError>`) see:
![image](https://user-images.githubusercontent.com/4574031/135904255-bef14c65-da00-4c8f-958c-ca3158d4a3ec.png)
which have to be `Result<string, DomainError>`.

We already had that topic last year, see this post: https://github.com/fsprojects/FsUnit/issues/146#issuecomment-572478732

I hope that helps. I'm hearing from you!

**Comment by purkhusid** [comment]
Hey! Thanks for taking your time responding to my issue! I figured that I just needed the type annotations, thanks again for taking your time!
