### ISSUE TITLE
ofCase doesn't handle None (represented as null)

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsUnit#191]
### Description

`None |> should be ofCase <@ None @>` doesn't work 

The problem is that `None` is represented as `null` and [the `x.GetType()` on this line](https://github.com/fsprojects/FsUnit/blob/8134d984ba5d1d9200dfac7f03e6dd5070ed15e0/src/Common.fs#L51)  gives a NullReferenceException.

### Expected behavior

Evaluates to `true`

### Actual behavior

NRE

### Known workarounds

Hand code checking for `None` in your tests

**Comment by CaptnCodr** [comment]
@dsyme This issue has been fixed in FsUnit v4.0.7.

**Comment by dsyme** [comment]
Thanks! cc @kathleendollard
