### ISSUE TITLE
Implementing Expecto

### ISSUE THREAD

**Issue by CaptnCodr** [fsprojects/FsUnit#197]
### Description

I came across [Expecto](https://github.com/haf/expecto) and discovered the possibilities behind it. 
We could implement Expecto because it has also a wide range of users.

### Actual behavior

Some users may not using FsUnit because FsUnit is currently not supporting Expecto.

### Feature

First of all, we could implement the basic features that are currently also implemented in FsUnit.
All operators are here: https://github.com/haf/expecto#expectations-with-expect

@sergey-tihon Do you agree or any objections?
I would start with it in the next week.

**Comment by sergey-tihon** [comment]
We already discussed this in 2018 https://github.com/fsprojects/FsUnit/issues/120 and find out https://github.com/haf/expecto/blob/main/Expecto/Flip.Expect.fs that is very close to FsUnit syntax.

I still do not see much value to compete. Maybe we just should link/mention recommendation for Expecto?

**Comment by CaptnCodr** [comment]
Yes, you're right. This is quite equal to FsUnit. 

> Maybe we just should link/mention recommendation for Expecto?

We can do that. How would that look like and where would you write that down?

**Comment by sergey-tihon** [comment]
I think that we can add Expecto page in Getting started section and mention that we do not provide FsUnit.Expect because there is a thing called Flip.Expecto that provides similar assertion syntax, link to the official docs and maybe add some simple code sample how it looks.

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1197905/151367106-864a1668-f0fd-4f8f-ab91-0bfcb2ff1658.png">

**Comment by CaptnCodr** [comment]
Or we just link it up there with no comment.
![image](https://user-images.githubusercontent.com/4574031/151513927-17f2427e-4857-45b1-9218-3f897232af68.png)

**Comment by sergey-tihon** [comment]
@CaptnCodr we can start from that.

But I think that this "Expecto Fluent API" is quite hard to find

**Comment by CaptnCodr** [comment]
Docs now have been updated.
