### ISSUE TITLE
`result |> should be (ofCase <@ Ok @>)` throws exception at runtime

### ISSUE THREAD

**Issue by BryanWilhite** [fsprojects/FsUnit#198]
### Description

```console
System.InvalidCastException
Unable to cast object of type 'Microsoft.FSharp.Core.FSharpResult`2[System.Tuple`2[System.Boolean,System.Text.Json.JsonElement],System.Text.Json.JsonException]' to type 'Microsoft.FSharp.Core.FSharpResult`2[System.Object,System.Object]'.
   at lambda_method25(Closure , Object )
   at FsUnit.Common.isOfCase@54.Invoke(a x)
   at NHamcrest.Core.CustomMatcher`1.Matches(T item)
   at Songhay.Dashboard.Bolero.Tests.SyndicationFeedTests.getAtomChannelTitle test(String elementName) 
```

### Repro steps

```fsharp
    [<Theory>]
    [<InlineData(nameof GitHub)>]
    [<InlineData(nameof StackOverflow)>]
    let ``getAtomChannelTitle test`` elementName =
        let result: Result<(bool * JsonElement),JsonException> =
            appJsonDocument.RootElement
            |> SyndicationFeedUtility.getFeedElement elementName

        result |> should be (ofCase <@ Ok @>)
```
### Related information 

```console
JetBrains Rider 2021.3.2
Build #RD-213.6461.51, built on December 22, 2021
Licensed to Bryan Wilhite
Subscription is active until August 12, 2022.
Runtime version: 11.0.13+7-b1751.21 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-27-generic
.NET 6.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    com.settler.rider.specflow (1.10.2)
    com.intellij.plugins.vscodekeymap (213.5744.3)
    com.intellij.resharper.azure (3.50.0.1314-2021.3)

Current Desktop: ubuntu:GNOME
```

**Comment by sergey-tihon** [comment]
This discussion should help https://github.com/fsprojects/FsUnit/issues/190#issuecomment-939333733

As you error message say

> Unable to cast object of type 'Microsoft.FSharp.Core.FSharpResult`2[System.Tuple`2[System.Boolean,System.Text.Json.JsonElement],System.Text.Json.JsonException]' to type 'Microsoft.FSharp.Core.FSharpResult`2[System.Object,System.Object]'.
 
`result` has type `Microsoft.FSharp.Core.FSharpResult`2[System.Tuple`2[System.Boolean,System.Text.Json.JsonElement],System.Text.Json.JsonException]`

`Ok` has type `Microsoft.FSharp.Core.FSharpResult`2[System.Object,System.Object]` (compiler was not able to infer generic params of Result type just from `Ok`

So in runtime `FsUnit` see 2 objects with different types and they cannot be equal.

**Comment by CaptnCodr** [comment]
or look at that issue #189 
You may have to add further type declarations to your code. 

Just try following:
```
result |> should be (ofCase <@ Result<(bool * JsonElement),JsonException>.Ok @>)
```

**Comment by BryanWilhite** [comment]
excellent! many thanks @sergey-tihon and @CaptnCodr!

it is working as expected:

![image](https://user-images.githubusercontent.com/5226627/152090533-a75b6014-bfc3-4ac4-9a88-1f5de994710e.png)
