### ISSUE TITLE
Simplify "should throw"

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FsUnit#20]
Currently, you have to use `ignore` to discard the result in the function and you need to get type using `typeof`:

    (fun () -> failwith "BOOM!" |> ignore) |> should throw typeof<System.Exception>

I think it would be neat if you could write just:

    (fun () -> failwith "BOOM!") |> should throw<System.Exception>

**Comment by Evangelink** [comment]
@sergey-tihon Do you care about retro compatibility? (i.e. should I keep the old method and create a new one?). I am about to do this quick PR.

**Comment by sergey-tihon** [comment]
@Evangelink Yes we care about backward compatibility.
I think that we can support this feature in new [FsUnit.Typed](https://github.com/fsprojects/FsUnit/pull/85/files#diff-558d23dbe88440f107e27e0c9e745db9R36) that is probably will be merged into FsUnit repo.

**Comment by Evangelink** [comment]
Ok cheers! I will have a look.

**Comment by Evangelink** [comment]
@sergey-tihon There is a shouldFail method line 36 (don't know how to link a portion of code) in your commit that already satisfy @tpetricek  request.
`(fun () -> failwith "BOOM!") |> shouldFail<exn>`

Don't think it is worth doing a shouldThrow that will do the same thing (rename current method?). I can add a shouldFailWithMessage method that will also check the error message if wanted.

**Comment by sergey-tihon** [comment]
Released in [v2.2.0-beta1](https://www.nuget.org/packages/FsUnit/2.2.0-beta1)
