### ISSUE TITLE
Pipelines are not correctly failing

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/FsUnit#204]
### Description

https://github.com/fsprojects/FsUnit/pull/203 at commit bd20cb8c996742f8ae5afebd86eb700dd306c282 resulted in https://github.com/fsprojects/FsUnit/runs/5778346102 which contains the following:

```
Starting target 'Format'
Formatted files: { Errors =
          [("/home/runner/work/FsUnit/FsUnit/tests/FsUnit.Xunit.Test/typed.shouldEqualTests.fs",
            Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (131,9)-(131,12) parse error The block following this 'let' is unfinished. Every code block is an expression and must have a result. 'let' cannot be the final code element in a block. Consider giving this block an explicit result.|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
```

That is, it correctly notes that [one of my added files](https://github.com/fsprojects/FsUnit/blob/bd20cb8c996742f8ae5afebd86eb700dd306c282/tests/FsUnit.Xunit.Test/typed.shouldEqualTests.fs) is invalid F#.

Despite this, the GitHub Actions pipelines all passed; it was sheer luck that I glanced through the logs.

It seems desirable to make it so that errors cause the pipeline to fail.

**Comment by CaptnCodr** [comment]
Is this resolved now?

**Comment by Smaug123** [comment]
If it is fixed, it was fixed by https://github.com/fsprojects/FsUnit/pull/205. I haven't verified that it is fixed.
