### ISSUE TITLE
Statically typed equality test

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FsUnit#21]
In an earlier version, there used to be `shouldEqual` primitive that beahaved like `y |> should equal x` but statically required `x` and `y` to have the same type.

I find that extremely useful - I was using some untyped equal constraints and it quite regularly caused trouble where test would compile, but fail - when I changed some API.

Can we have this function (or some alternative) back?

**Comment by sergey-tihon** [comment]
Released in [v2.2.0-beta1](https://www.nuget.org/packages/FsUnit/2.2.0-beta1)
