### ISSUE TITLE
error FS0074: The type referenced through 'NHamcrest.IMatcher`1' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by Vasar007** [fsprojects/FsUnit#212]
### Description

Hello! Recently I received notification from dependabot to update FsUnit from 5.0.1 to 5.0.2. I have CI in my repository. So, CI check failed with a follow error in the logs:

`error FS0074: The type referenced through 'NHamcrest.IMatcher'1' is defined in an assembly that is not referenced. You must add a reference to assembly 'NHamcrest'.`

You can see the full logs of CI check [here](https://ci.appveyor.com/project/Vasar007/acolyte-net/builds/44470405).

### Repro steps

1. Create a test project and reference .NET 4.7.2
2. Install FsUnit 5.0.2
3. Try to build a project

### Expected behavior

The test project is successfully compiled on step 3. If this is the expected behavior, I would like it to be documented. I looked at the documentation but didn't find anything about this issue.

### Actual behavior

Build failed with this error:

`error FS0074: The type referenced through 'NHamcrest.IMatcher'1' is defined in an assembly that is not referenced. You must add a reference to assembly 'NHamcrest'.`

### Known workarounds

I fixed my build when I explicitly installed `NHamcrest.XUnit` package of version 2.0.1 for the test project. But I don't use logic from this NuGet package in my project (maybe only implicitly through the FsUnit  library). So, this workaround looks like a crutch =)

**Comment by CaptnCodr** [comment]
Hey @Vasar007, thank you for opening an issue. I'll look into that.

**Comment by CaptnCodr** [comment]
This issue is fixed in v5.0.3, that is now available at Nuget.
