### ISSUE TITLE
[Feature request] Creating custom constraints

### ISSUE THREAD

**Issue by C0DK** [fsprojects/FsUnit#215]
### Description

I'm new to both FsUnit and F# in general. But I like this framework so far. I am, however, hoping I could add some custom constraints, and I was wondering how to map that into this framework. I have used NUnit to some extent and used their custom constraints a bunch. I was hoping to do something like

```fsharp
somePerson
|> WithName SomeName
|> Should HaveName (Equal SomeName)
```

But need to figure out how to convert a delegate to a constraint to make it possible to have `HaveName`.

My actual question is less so about how i would achieve my task, but more about that this sort of extensibility isn't covered in the documentation as far as i can see.

**Comment by CaptnCodr** [comment]
Hello @C0DK ,
it depends what type `somePerson` is.

I assume that `somePerson` is a complex type like a record or class. In case of that `WithName` and/or `HaveName` must support the same type as `somePerson`.

Even so, I recommend assertions as simply as possible e.g.:
```fsharp
type Person = { Name: string; Age: int }

let somePerson = ... // function that returns: { Name = "test"; Age = 34 }

somePerson.Name
|> should equal "test"

// and perhaps:
somePerson.Age 
|> should equal 34
```

**Comment by CaptnCodr** [comment]
> Should I just use `let` more rather than doing everything as a singular expression?

No, that was just an example on my side for better readability. 
You can also write from my example: 
```
somePerson
|> fun p -> p.Name
|> should equal "test"
```

An extra constraint or operator in FsUnit would be too special, btw. 
Use single/short functions to have a little toolset in your implementations.

**Comment by C0DK** [comment]
alright. Consider it closed then :) I might raise another ticket if i have a more complex case. In a c# project where we use NUnit, we do have custom constraints for specific things, like checking whether a StatusCode is "Succesful" (200 <= x < 300) based on NUnits custom constraints https://docs.nunit.org/articles/nunit/extending-nunit/Custom-Constraints.html - and i think that was my offset. but in this case i do see your point. 

Thank you :) I also didn't think of using a `fun p -> p.Name` rather than an explicit function defined above. neat!
