### ISSUE TITLE
Deep equality for C# types

### ISSUE THREAD

**Issue by AlexeyRaga** [fsprojects/FsUnit#219]
### Description

In F# code we often have to use data types that are defined in C#.  These types usually don't have equality defined, and therefore only get referential equality.

It would be useful if `FsUnit` would provide a mechanism to still be able to structurally compare these types, similarly to how `FluentAssertions` does in its `BeEquivalentTo` method for C#:

```csharp
actual.Should().BeEquivalentTo(expected, "reason")
```

### Repro steps

1. Have a C# defined class like:
```csharp
public sealed class Persion { 
  public string Name { get; set; }
  public int Age { get; set; }
}
```

2. Wrap it in F# union:

```fsharp
type User = User of Person

// Notice that the person inside is "the same"
let userA = User (Person(Name = "a", Age = 1))
let userB = User (Person(Name = "a", Age = 1))
```

3. Compare these two values:

```fsharp
// this says "no"
userA |> should equal userB
```

### Expected behavior

I suggest that it'd be possible to have an operation that would allow the previous example to pass. 
It can be named `beEquivalentTo` or somehow else.

The operation can detect F# types (or presence for equivalence) and do what `equal` does, otherwise it can do what `FluentAssertions` does currently (takes a set op public fields and properties and runs comparison on them).

### Actual behavior

The given example fails the test

### Known workarounds

I can't come up with a workaround that can work for an arbitrarily nested case.

**Comment by CaptnCodr** [comment]
Hello @AlexeyRaga, 
FsUnit does support for structural equality. You can use `records` and classes that support comparison.
Here's the implementation: https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.NUnit/Equality.fs#L24

Another workaround would be to assert every single property: 
```
userA.Name |> should equal userB.Name
userA.Age |> should equal userB.Age
```

**Comment by AlexeyRaga** [comment]
@CaptnCodr Yes and no :)

> FsUnit does support for structural equality.

It only supports structural equality via `IStructuralEquatable`, as you pointed. I am, in contrast, talking about supporting structural equality that does not require implementing this interface.

For example, when there is an existing C#/.NET type that does not provide `IStructuralEquatable` (like my `Person` type above), it is still useful to be able to compare it structurally. Other assertion libs (noticeably super powerful `FluentAssertions`) can do that.

> Another workaround would be to assert every single property

As I said, this solution doesn't generalise well. 
One problem is when an "outer" type does have structural equality but "inner" type does not. 

In this type
```fsharp
type User = User of Person
```

`User` will have `IStructuralEquatable`, but when it comes to comparing `Person` inside, it will still only use referential equality because `Person` isn't `IStructuralEquatable`. This mix isn't handled well.

Now consider that you want to assert equivalence of collections of `Person`s or `User`s.

What I am thinking about is the ability to explicitly instruct `FsUnit` to ignore possibly defined equality (even if exists) and always use derived method for structural equality.

By "derived method" I mean to do something like:
- For product types: Take public properties and fields and compare recursively
- For sum types: Take union case fields and recursively compare those

**Comment by sergey-tihon** [comment]
FsUnit is an assertion library that supports DSL on top of popular unit testing frameworks. I think that `equality` should be provided by the type (e.g. `Person`). 

If you need equality for C# types (and cannot define them in F# ☺️) you may search for C# source generator library that will generate proper equality for your type ([like this for example](https://github.com/diegofrata/Generator.Equals))

**Comment by AlexeyRaga** [comment]
> I think that equality should be provided by the type

I couldn't agree more. But in reality there are 3rd party libs that are being used, and classes that are out of our control, and for these scenarious it'd be helpful.

> library like [DeepEqual](https://github.com/jamesfoster/DeepEqual) and tiny F# layer on top for assertions

Thanks, I'll double check. Last time I checked (long time ago) it wasn't F# types friendly... So mixed things like C# type inside F# union didn't work...

**Comment by CaptnCodr** [comment]
@AlexeyRaga I'll close this here. This is out of our scope.
