### ISSUE TITLE
FsUnit cannot be run

### ISSUE THREAD

**Issue by haf** [fsprojects/FsUnit#23]
Steps to reproduce:

`install-package fsunit`

```
module test.mod
open NUnit.Framework
open FsUnit
let [<Test>] smoke () = 1 |> should equal 1
```

Have ReSharper 7.1 installed. Rightclick test project, select 'Run Unit Tests':

```
System.MissingMethodException : Method not found: 'Void FsUnit.TopLevelOperators.should(Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!1>, !!0, System.Object)'.
   at test.mod.smoke()
```

Further testing done: downgrading NUnit to v2.6.2 from installing version 2.6.3.

**Comment by evilz** [comment]
This issue is back using FSharp 3.1  (FSharp.Core 4.3.1.0) on .net 4.5.3
```
System.MissingMethodException : Method not found: 'Void FsUnit.TopLevelOperators.should(Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!1>, !!0, System.Object)'.
```

**Comment by mausch** [comment]
@evilz add this NuGet package to your project: https://www.nuget.org/packages/FSharp.Core

**Comment by ksmigiel** [comment]
I had the same issue, but below config helped me:
``` xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NUnit.Framework" publicKeyToken="96d09a1eb7f44a77" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.3.13283" newVersion="2.6.3.13283"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by 7sharp9** [comment]
So is everyone using an appconfig to patch this?

**Comment by rneatherway** [comment]
It worked for me in the end, but I think it should work out of the box.

**Comment by 7sharp9** [comment]
I have to use assembly redirects to get it to work.

If I recompiled fsunit with a .Net 4.5 compilation (rather than .Net 3.5) then there was no issues.  Im not sure why there isn't net45 versions that just work, shouldn't have to have an app.config whenever I want to use it :-(

**Comment by paulyoung** [comment]
I'm getting `System.MissingMethodException : Method not found: 'FsUnit.TopLevelOperators.equal` despite my `app.config` already being set to the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="nunit.framework" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.4.14350" newVersion="2.6.4.14350" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by sideeffffect** [comment]
hi, I seem to have the same problem:

```
System.MissingMethodException : Method not found: 'Void FsUnit.TopLevelOperators.should(Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!1>, !!0, System.Object)'.
```

but sadly neither [adding `FSharp.Core`](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.9) nor [adding `app.config`](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.10) helped. is there another way around this?

**Comment by rneatherway** [comment]
The app.config file has to be part of a particular project. Take a look at http://fsprojects.github.io/FsUnit/#Visual-Studio-11-Support and how I did it here: https://github.com/fsprojects/Projekt/tree/master/tests/Projekt.Tests

**Comment by sideeffffect** [comment]
hmm, it's [still failing](https://ci.appveyor.com/project/sideeffffect/fsharphello/build/0.0.1.11)
I tried
```
PM> Add-BindingRedirect FSharpHello.Tests
```
in MonoDevelop *Package Console Extension*, but I got

```
Command 'Add-BindingRedirect' not found.
```

so I just moved the file `App.config` to the right place.

**Comment by misterspeedy** [comment]
Just a heads up - when I installed the latest beta of FSUnit (1.4.0.0-beta3) this issue recurred even with the redirects in place.  When I downversioned to 1.3.1.0 it went away again.

**Comment by rneatherway** [comment]
@sideeffffect that command only works in the Visual Studio console, which I had assumed you were using.

@misterspeedy it might be worth trying @sergey-tihon's fix in that PR above, it makes sure all the right redirects are in place in the right places and being used.

**Comment by sergey-tihon** [comment]
@misterspeedy Could you please share your build log and redirects? or even create a new issue.
`1.4.0.0-beta3` differs greatly from `1.3.1.0`. It compiled for net45 and uses latest FSharp.Core 4.4.0.0
You need to change redirects to make it works.

**Comment by misterspeedy** [comment]
Oh, ta - it's probably just the redirects I was using.  I'll re-install the
beta and try updating the redirects.  Ta.

**Comment by sergey-tihon** [comment]
@misterspeedy Please share your results. Thx

**Comment by 7sharp9** [comment]
Does fsunit need to target the very latest FSharp.Core?

Generally F# ecosystem libraries should generally target the earliest, most portable version of FSharp.Core feasible.

**Comment by sergey-tihon** [comment]
I think that `FsUnit` should target the same version as `FsCheck` use, to simplify integration.
https://github.com/fsprojects/FsUnit/issues/72#issuecomment-127890791

**Comment by 7sharp9** [comment]
Why does FSUnit use 4.4?
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html

**Comment by sergey-tihon** [comment]
Am I right that you think that `FsUnit` should depend on [FSharp.Core/3.1.2.5](https://www.nuget.org/packages/FSharp.Core/3.1.2.5) and be build using this version of `FSharp.Core`?

**Comment by asibahi** [comment]
I am running into this issue as well. Tried adding `app.config` to no avail [See here](http://stackoverflow.com/questions/39608983/fsunit-unable-to-test-portable-library-due-to-it-and-test-project-having-differ/39609814?noredirect=1#comment66530523_39609814)
