### ISSUE TITLE
Is FSharp.Core 6.0.7 really the lowest dependency for FsUnit?

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/FsUnit#235]
### Description
In version [5.1.0](https://www.nuget.org/packages/FsUnit.xUnit/5.1.0#dependencies-body-tab) the F# Core dependency is `>= 5.0.2`, which is very convenient for a test library, as it allows seamless testing for a large variety of F# versions.

From version [5.2.0](https://www.nuget.org/packages/FsUnit.xUnit/5.2.0#dependencies-body-tab) this jumps to `>= 6.0.7`, which is a big leap and for a bunch of projects (mostly projects that need to use "lowest denominator", like NuGet packages and libs), this causes warnings like these

> warning NU1605: Detected package downgrade: FSharp.Core from 6.0.7 to 6.0.3.

### Repro steps

Repro is simple: create a lib that uses an older F# Core, then create a test project with FsUnit for it.

### Expected behavior

Lowest possible dependency, as this library is widely used. While I understand that a bump to 6.x is necessary at some point (should perhaps be a major version upgrade?), for instance for using `task`, I would argue that `6.0.2` or thereabouts should be fine.

### Actual behavior

See above.

### Known workarounds

Use lower dependency, or force-reference F# Core to remove the warning.

**Comment by CaptnCodr** [comment]
Hi @abelbraaksma, 
you're right. I didn't changed back the FSharp.Core version as I dropped the net7.0 some updates ago.
I'll change this in the next days.

**Comment by abelbraaksma** [comment]
Thanks, let me know if I need to test anything for you, happy to help!

**Comment by CaptnCodr** [comment]
Hey @abelbraaksma,
this has been released in v5.3.1. 

Thank you for your issue! 🙂
