### ISSUE TITLE
Method not found error on NUnit 4 

### ISSUE THREAD

**Issue by lucasteles** [fsprojects/FsUnit#256]
### Description

This project sets the NUnit dependency as `NUnit ≥ 3.14.0` but, when running an assertion on a project with `NUnit 4.0.0` I am getting a reflection error:

```
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Assert.That(System.__Canon, NUnit.Framework.Constraints.IResolveConstraint)'.
   at FsUnit.TopLevelOperators.should[a,a](FSharpFunc`2 f, a x, Object actual)
   at Astrorex.Api.Tests.EscolaControllerTests.Deve adicionar role "aluno" no usuario() in C:\d\Astrorex.Api\tests\Astrorex.Api.Tests.Integracao\EscolaControllerTests.fs:line 294
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Repro steps

1. Install NUnit 4 and FSUnit
2. Run an assertion

### Expected behavior

Should work without errors

### Actual behavior

Given reflection error

### Known workarounds

Downgrade NUnit

**Comment by CaptnCodr** [comment]
Hi @lucasteles, it seems that FsUnit isn't compatible with `NUnit 4.0` at the time being. I will migrate FsUnit in the next few days to the latest version of NUnit. 
Please use `NUnit 3.14.0` as you already described in the workarounds.

Thank you for the patience.

**Comment by CaptnCodr** [comment]
An upgrade to `NUnit 4.0` is due to an issue with the compatibility not possible.
I filed an issue for that: https://github.com/nunit/nunit/issues/4568

I keeps you updated.

**Comment by CaptnCodr** [comment]
I will release a fix for this issue, that you don't even upgrade NUnit to the next major version when FsUnit is installed.

Next, I probably will migrate to `NUnit 4.0` and create a new major version.

**Comment by CaptnCodr** [comment]
Hey @lucasteles,
[`FsUnit 6.0.0-alpha1`](https://www.nuget.org/packages/FsUnit/6.0.0-alpha1) is now available. 
You could test this version out if everything works as expected. Leave a message if you had.

**Comment by CaptnCodr** [comment]
FsUnit v6.0 is now available!
