### ISSUE TITLE
FsUnit vNext

### ISSUE THREAD

**Issue by CaptnCodr** [fsprojects/FsUnit#258]
Developments of FsUnit's dependencies are going on and FsUnit needs to adapt sometimes. (https://github.com/nunit/nunit/issues/4568)

As I mentioned here: https://github.com/fsprojects/FsUnit/issues/256#issuecomment-1832199569
> I will make a plan for the NUnit 4.0.0 migration. NUnit 3.X will be supported for the time being.

In the meantime of discussing in the NUnit repository I made a little plan to migrate to `NUnit v4` + maintaining `NUnit v3.X` side-by-side. `NUnit v3.X` will be maintained for bugfixes etc.

I researched some thingies, evaluated those and that's my plan:
- Project `FsUnit.NUnit` will be migrated to `NUnit v4`, stays `FsUnit` on nuget, exported for ~~`net462`~~ & `net6.0`
~~- New Project `FsUnit.NUnit3` gets the old code, gets `FsUnit.NUnit3` on nuget, exported for `netstandard2.0` & `net6.0` (as before)~~
- Both `FsUnit.NUnit` and `FsUnit.NUnit3` get the same nuget version every update
- Can be built side-by-side in existing solution

Further updates:
- Upgrading MsTest to 3.x
- Clean ups

Recommended FsUnit vNext is `6.0.0`, release eta mid January 2024

Checklist:
- [X] `FsUnit.NUnit` `NUnit v4` migration ([FsUnit 6.0.0-alpha1](https://www.nuget.org/packages/FsUnit/6.0.0-alpha1))
~~- New Project `FsUnit.NUnit3`~~
- [X] Upgrade to `MsTest 3.x` ([FsUnit 6.0.0-alpha2](https://www.nuget.org/packages/FsUnit/6.0.0-alpha2))
- [X] Clean ups ([FsUnit 6.0.0-alpha3](https://www.nuget.org/packages/FsUnit/6.0.0-alpha3))
- [x] Update docs (#262)

@sergey-tihon Do you have some suggestions or more points for the checklist?

**Comment by CaptnCodr** [comment]
Thank you for your evaluation, I respect that.

**Comment by nojaf** [comment]
Hello, we would like to update Fantomas to NUnit 4 and we would require a new version of FsUnit with the bump. Please consider releasing an alpha package when you have something. Thanks!

**Comment by CaptnCodr** [comment]
Hi Florian, I will notify you, when there's an alpha version!

**Comment by CaptnCodr** [comment]
@nojaf Hi Florian, [`FsUnit 6.0.0-alpha1`](https://www.nuget.org/packages/FsUnit/6.0.0-alpha1) is now available.
Please give me feedback if everything works as expected.

**Comment by nojaf** [comment]
Works for us! Thanks Constantin!

**Comment by CaptnCodr** [comment]
FsUnit v6.0 is now available!
