### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by snuup** [fsprojects/FsUnit#265]
I would like to build the project but fail to do so. 

The build instructions link to GitPod, Opened an account there but have no idea where I can find build instruction to FsUnit there. This is all I see there:

![image](https://github.com/fsprojects/FsUnit/assets/61933552/0be92f40-ac7f-4e46-9325-4ef6f34de2ca)

Maybe you can place the instructions simply here in the readme as well?

**Comment by sergey-tihon** [comment]
I think that we should remove the link to GitPod, because we do not use it by ourselves and may be even broken...

Build should be as simple as run `./build.sh` or `build.cmd` (depending on your platform)
