### ISSUE TITLE
Add support for `xunit.v3`

### ISSUE THREAD

**Issue by meenzen** [fsprojects/FsUnit#296]
### Description

xUnit V3 has been released on 2024-12-16. Release announcement: https://xunit.net/releases/v3/1.0.0

**Comment by CaptnCodr** [comment]
Hi @meenzen, 
I will tackle this soon. Thank you for referencing.

**Comment by CaptnCodr** [comment]
Hey @meenzen,
`xunit.v3` is now part of `FsUnit.Xunit 7.0` and has been released already.

Happy holidays! 🎅🏻
