### ISSUE TITLE
(should contain) as argument to list.iter

### ISSUE THREAD

**Issue by remkoboschker** [fsprojects/FsUnit#35]
using xunit

``list2 |> Seq.iter (list1 |> (should contain) )`` does not work

however ``list2 |> Seq.iter (fun x - > list1 |> should contain x) `` does 

``(list |> should contain)`` returns a function of type ``object -> unit`` so I do not understand why I get a match exception.

**Comment by sergey-tihon** [comment]
## Expression 2
If you remove pipe operator from your second expression
```fsharp
list2 |> Seq.iter (fun x -> list1 |> should contain x)
```
you will get
```fsharp
list2 |> Seq.iter (fun x -> should contain x list1)
```

## Expression 1

In the same time, if you add param to the function from first expression
```fsharp
list2 |> Seq.iter (list1 |> (should contain) )
```
you will get
```fsharp
list2 |> Seq.iter (fun x -> (list1 |> (should contain)) x)
```
that is equal to
```fsharp
list2 |> Seq.iter (fun x -> (should contain list1) x)
```
that is equal to 
```fsharp
list2 |> Seq.iter (fun x -> should contain list1 x)
```


## Conclution

Now it should be obvious that they are two different expressions:
```fsharp
list2 |> Seq.iter (fun x -> should contain list1 x)
list2 |> Seq.iter (fun x -> should contain x list1)
```
