### ISSUE TITLE
the assembly is not signed

### ISSUE THREAD

**Issue by ovidiudeac** [fsprojects/FsUnit#43]
We are using it in a signed assembly and it cannot be loaded otherwise

**Comment by bentayloruk** [comment]
@ovidiudeac I have the same problem and workaround it [using this](https://www.nuget.org/packages/Nivot.StrongNaming/).

**Comment by bentayloruk** [comment]
BTW - I don't rely on strong names for security.  However, I need to strong name the test assembly in order to allow it access to some internals of a strong named assembly, using `InternalsVisibleTo`.

**Comment by sergey-tihon** [comment]
But there are no real reason to sign `FsUnit` assemblies and we are not going to do it for now.
