### ISSUE TITLE
NuGet package lib/net40 contains .Net 2.0 binary

### ISSUE THREAD

**Issue by cdrnet** [fsprojects/FsUnit#44]
Currently there are separate assemblies in the FsUnit 1.3.0.1 NuGet package:

* lib/net20: built against .Net 2.0, references FSharp.Core 2.3.0.0
* lib/net40: built against .Net 2.0, references FSharp.Core 2.3.0.0

Would it be possible to keep the net20 as is but change the net40 one to build against .Net 4.0 and reference FSharp.Core 4.3.0.0?

I have a binding redirect issue in one of my projects where I need to redirect to FSharp.Core 2.3.0.0 for .Net 3.5 and to FSharp.Core 4.3.1.0 for all other platforms, but this does not work with FsUnit as it will always try to load the 2.3.0.0 one even in .Net 4.0 - which then conflicts with the other dependencies or fails to load entirely. In other words, since both reference exactly the same version, I cannot treat them separately for .Net 2.0 and .Net 4.0.

**Comment by sergey-tihon** [comment]
@cdrnet Do you think we should keep supporting .Net 2.0 for NUnit?

MSTest requires .NET 4.0
xUnit 2 requires .NET 4.5

**Comment by sergey-tihon** [comment]
I think that we should update `FsUnit.NUnit` to `net45`
in order to play nicer with `FsCheck` that currently require `net45` profile
![image](https://cloud.githubusercontent.com/assets/1197905/9041761/90b05090-3a12-11e5-93e0-d88ee881b7a7.png)

**Comment by cdrnet** [comment]
Thanks - the 4.5 upgrade is fine for me (I'll have to keep the old version for my .Net 3.5 builds but that's ok - seems I won't have to support that one much longer either).

**Comment by cdrnet** [comment]
Turns out this is now blocking me from updating my projects to NUnit3 :(

**Comment by sergey-tihon** [comment]
do you need `FsUnit` for `.net 2.0`?

if you use `Paket` you can [reference just one file](http://fsprojects.github.io/FsUnit/Paket.html) and be runtime independent.

**Comment by cdrnet** [comment]
Ah thanks, yes, that should work for me!

**Comment by sergey-tihon** [comment]
@cdrnet  You may be also interested in new statically typed operators
http://fsprojects.github.io/FsUnit/FsUnitTyped.html
