### ISSUE TITLE
is there a better way to match against patterns?

### ISSUE THREAD

**Issue by theburningmonk** [fsprojects/FsUnit#47]
Right now, I'm using a `match ... with` clause with the pattern I want (e.g. I don't care about all the items in a tuple) manually.

```
    match f() with
    | _, _, _, 42 -> true
    | _ -> false
    |> should equal true
```

which is very clumsy. Is there a better way to do this currently?

In Eunit, I'd use [?assertMatch](http://www.erlang.org/doc/apps/eunit/chapter.html#Assert_macros) which uses macros (which we don't have in F#), is there some way to achieve the same effect in F#?

**Comment by sergey-tihon** [comment]
Can you propose better syntax ?

```fsharp
match f() with
    | _, _, _, 42 -> 
      true |> should equal true
    | _ -> failwith "unexpected result"
```

**Comment by niwrA** [comment]
can't you basically write a function that would accept a function and a match pattern, and that fails if the function fails to match the pattern?

so in pseudocode: 
assert that f() matches (_,_,_,42)

**Comment by sergey-tihon** [comment]
Closed as an old issue (without realistic implementation ideas)
