### ISSUE TITLE
The NuGet package is outdated and does not match the documentation.

### ISSUE THREAD

**Issue by ane** [fsprojects/FsUnit#48]
I'm using version 1.3.0.1, the latest version available from NuGet, It's missing the choice matcher in #39, but it is described in the documentation as a feature.

**Comment by sergey-tihon** [comment]
What package have you used?
If NUnit one, please try [FsUnit 1.3.1-beta](https://www.nuget.org/packages/FsUnit/1.3.1-beta) it should be up-to-date

**Comment by sergey-tihon** [comment]
Latest version is on Nuget & should match new documentation http://fsprojects.github.io/FsUnit/index.html & http://fsprojects.github.io/FsUnit/reference/index.html
