### ISSUE TITLE
Failed equality assertion should use F# value formatter

### ISSUE THREAD

**Issue by et1975** [fsprojects/FsUnit#54]
ToString() on values that failed equality assertion is often quite useless, can we have "%A" formatter applied instead?

**Comment by sergey-tihon** [comment]
Am I right that this is a fix https://github.com/fsprojects/FsUnit/pull/60 ?

**Comment by et1975** [comment]
Yes, sorry, should have linked it.

**Comment by sergey-tihon** [comment]
Released with [FsUnit 1.4.0-beta](https://www.nuget.org/packages/FsUnit/1.4.0-beta)
