### ISSUE TITLE
Create new docs for FsCheck integration

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#72]
We definitely should create two new guild for FsUnit site
- `FsUnit` + `FxCheck` + `NUnit`
- `FsUnit` + `FsCheck` + `XUnit`

// https://github.com/sideeffffect/FSharpHello/pull/1#issuecomment-127538713

**Comment by sergey-tihon** [comment]
I think that would be nice to compile `FsUnit` using the same version if `FSharp.Core` that `FsCheck` use. Latest beta of `FsUnit` compiled using `FSharp.Core` 4.4.0.0, but `FsCheck` compiled using `4.3.1.0`

@kurtschelfthout do you have plans to use `FSharp.Core` 4.4.0.0 in `FsCheck`?

**Comment by kurtschelfthout** [comment]
Not immediately, there doesn't seem to be a compelling reason. When things settle down a bit probably I'll find some excuse…
