### ISSUE TITLE
fsunit assembly is not signed with a strong name

### ISSUE THREAD

**Issue by awostenberg** [fsprojects/FsUnit#77]
In using fsunit from a strongly-named assembly I get the folllowing error

`1) Test Error : TryFsunit.lib1.hello
   System.IO.FileLoadException : Could not load file or assembly 'FsUnit.NUnit, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HR
ESULT: 0x80131044)
   at TryFsunit.lib1.hello()`

Nunit works fine. It's just FSunit that isn't signed. There are many ways to sign an assembly in the FSUnit build process -- see [msdn article](https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx)

To reproduce
1. create a small library project. See (1)
2. add fsunit from nuget to the project
3. add any test
4. sign that library with a strong name. (There are many ways to do that. I used the 	`<OtherFlags>--keyfile:SomeSignature.snk</OtherFlags>`  method in the .fsproj).   See (2)
5. build with msbuild
6. run from command line "nunit-console.exe"
7. you will see the above error "Could not load file or assembly 'FsUnit.NUnit'...A strongly-named assembly is required."

(1) Sample library1.fs fragment

    let add a b = a + b
    // this fails at test runtime
    [<Test>] 
    let hello2() = add 2 3 |> should equal 5
    // This works, which means: nunit is strong signed. But fsunit is not. 
    [<Test>] 
    let hello() =
        let n = add 2 3
        Assert.That(n,Is.EqualTo(5))

(2) Sample .fsproj file fragment with  `<OtherFlags>`

    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <OutputType>Library</OutputType>
      ....
      <OtherFlags>--keyfile:SignKeyLifeQuest.snk</OtherFlags>
    </PropertyGroup>

**Comment by sergey-tihon** [comment]
@awostenberg Why do you sign your test assemblies? Please describe your case.

We think that there is no real need to do it, so we probably not going to sign `FsUnit` right now.
Reed more https://github.com/fsprojects/FsUnit/pull/42 and https://github.com/fsprojects/FsUnit/issues/43

There are couple of workarounds (if you cannot avoid signing test assemblies):

- You can sign FsUnit on your side using [Nivot.StrongNaming](https://www.nuget.org/packages/Nivot.StrongNaming/)
- You can use [Lightweight FsUnit with Paket](http://fsprojects.github.io/FsUnit/Paket.html) and do not reference NuGet package at all.

**Comment by awostenberg** [comment]
Yes it is unusual to sign test assemblies. We do it for convenience to the developer building and learning the system. The orthodox way is to have independent test assemblies. We include tests right in the customer facing code assemblies.  This is convenient for the developer who sees the test code right near the feature code, and tests illustrate how to use the feature code.   But customer facing assemblies are signed with a strong name. And so anything they use needs that. I stress it works for NUnit. Just not FSunit.  I'll look at the workarounds. But please reconsider.

**Comment by jwittner** [comment]
In order to expose internal types for testing to assemblies via the InternalsVisibleTo attribute from a signed assembly, those assemblies must also be signed. Right now I can't do that =(.

**Comment by sergey-tihon** [comment]
As workaround you can include `FsUnit.fs` or `FsUnitTyped.fs` file to your test project and do not reference FsUnit package.
- http://fsprojects.github.io/FsUnit/Paket.html
- http://fsprojects.github.io/FsUnit/FsUnitTyped.html#What-is-FsUnitTyped

**Comment by jwittner** [comment]
@sergey-tihon Thanks for the idea! Love open source. =)
