### ISSUE TITLE
Method not found 'Void FsUnit.TopLevelOperators.should'

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FsUnit#87]
Builds, but fails at run time.

    let result = 
        ["est"; "1test"; "est1"] 
        |> Set.ofList

    x'.Value |> should equal result

nunit.framework.dll 3.0.5813.39031
FsUnit.NUnit.dll 2.0.0.0

``Assert.AreEqual(x'.Value, result)`` works

**Comment by sergey-tihon** [comment]
Any ideas how can I reproduce it? It works on my machine...
What version of `Fsharp.Core.dll` do you use? Maybe we need to configure assembly redirects?

**Comment by jackfoxy** [comment]
I'll look at it some more this week.

**Comment by jackfoxy** [comment]
Our old friend binding redirect. My project is running FSharp.Core 4.4.

Should I add a note about this in the docs? I have a minor issue for a PR anyway.

**Comment by sergey-tihon** [comment]
Yes, please. it would be awesome.
