### ISSUE TITLE
FsUnitTyped.shouldEqual flips `expected` and `actual`

### ISSUE THREAD

**Issue by jmmk** [fsprojects/FsUnit#95]
With FsUnit, as seen in the [documentation](https://fsprojects.github.io/FsUnit/NUnit.html), a unit test is written:
```fsharp
actual |> should equal expectedValue
```

We can verify by looking at the [source code of Nunit's `EqualityConstraint`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/EqualConstraint.cs#L42) that indeed `equal` should be given the `expected` value.

---

The [documentation for FsUnitTyped](https://fsprojects.github.io/FsUnit/FsUnitTyped.html) is a little sparse, but it still seems to follow the pattern "actual on the left; expected on the right".

However, if we look at the [source code of `shouldEqual` in FsUnitTyped](https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.NUnit/FsUnitTyped.fs#L10), we can see that it is defined with `expected` as the first argument and `actual` as the second.

So `actual |> shouldEqual expectedValue` will (on failure) print out:

```
Expected: actual
Actual: expected
```

I'm not sure if the arguments are flipped for the other functions in FsUnitTyped or if this just affects `shouldEqual`. I haven't used any of the others.

**Comment by sergey-tihon** [comment]
At least with `FsUnitTyped` everything is OK. We do not use equality from `NUnit`

```fsharp
    [<DebuggerStepThrough>]
    let shouldEqual (expected : 'a) (actual : 'a) =
        Assert.IsTrue((expected = actual), sprintf "Expected: %A\nActual: %A" expected actual)
```

so the call ``actual |> shoutEqual expected`` will print correct output

**Comment by jmmk** [comment]
@sergey-tihon I used NUnit only as an example to show the order of the arguments: `actual` on the left, `expected` on the right.

But the way `shouldEqual` is defined is with `expected` on the left, `actual` on the right.

**Comment by sergey-tihon** [comment]
Sorry, but seems that I do not understand the issue.
It how `|>` (pipe) operator works. (Example contains two equal execution of function `f`)
```fsharp
let x = f a b
let x = b |> f a 
```
So if you decide to use `shouldEqual` without pipe operator it will be
```
shouldEqual expected actual
shouldEqual 4 (2+2)
```
with pipe operator
```fsharp
actual |> shouldEqual  expected
(2+2) |> shouldEqual 4
```

**Comment by jmmk** [comment]
I just made another test case and it seems to be working correctly. I must have been mistaken, sorry!
