### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by gabornemeth** [fsprojects/FsUnit#98]
### Description

Is there any chance to support other platforms than net45?
It would be nice to be able to add FsUnit to PCL, Xamarin, etc. projects?
I'd gladly give you a hand, too.

### Repro steps

Create a PCL/Xamarin.iOS/Xamarin.Android/.. project and try add FsUnit as a nuget package.

**Comment by sergey-tihon** [comment]
I will keep it open and I guess that we may try to target `netstandard` very soon.
But if you use it with `NUnit` you need only one platform independent file, that is very easy to reference with `Paket` - http://fsprojects.github.io/FsUnit/Paket.html
or you could try new `FsUnitTyped` as well using `Paket` - http://fsprojects.github.io/FsUnit/FsUnitTyped.html

**Comment by sergey-tihon** [comment]
@gabornemeth Could you please try latest beta [3.0.0-beta1](https://www.nuget.org/packages/FsUnit/3.0.0-beta1), version compiled to `netstandard` should work on all platforms

**Comment by gabornemeth** [comment]
I have tried on Android. Nuget package is successfully added. Tests are compiled as well.
Great job! Thank you.

**Comment by sergey-tihon** [comment]
Thank you! Cool!
